<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>FlyingRaijin.Controller</AssemblyName>
    <RootNamespace>FlyingRaijin.Controller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Remote" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlyingRaijin.Messages\FlyingRaijin.Messages.csproj" />
  </ItemGroup>

</Project>
