<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>FlyingRaijin.Engine</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Torrent\Multi\**" />
    <Compile Remove="Torrent\Single\**" />
    <EmbeddedResource Remove="Torrent\Multi\**" />
    <EmbeddedResource Remove="Torrent\Single\**" />
    <None Remove="Torrent\Multi\**" />
    <None Remove="Torrent\Single\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Remote" />
    <PackageReference Include="Akka.Streams" />
    <PackageReference Include="IdGen" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="System.Threading.Channels" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlyingRaijin.Messages\FlyingRaijin.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bencode\Write\" />
  </ItemGroup>

</Project>
